{{- range $key, $value := .Values.consoleLink }}
{{- if $value.createLink | default true }}
apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: {{ $.Values.appName }}-console-link
  namespace: {{ $.Values.namespace }}
spec:
  applicationMenu:
    section: {{ $value.section }}
    imageURL: {{ $value.base64image }}
  href: 'https://{{ $.Values.appName }}-route-{{ $.Values.namespace }}.{{ coalesce $.Values.global.localClusterDomain $.Values.global.hubClusterDomain }}'
  location: {{ $value.location }}
  text: {{ $value.text }}

{{- end }}
{{- end }}

#http://credit-fraud-detection-demo-route-credit-fraud-model.apps.cluster-7dfg8.7dfg8.sandbox258.opentlc.com/
#http://credit-fraud-detection-demo-route-credit-fraud-model.apps.cluster-7dfg8.7dfg8.sandbox258.opentlc.com/

#http://credit-fraud-detection-demo-route-credit-fraud-model.apps.cluster-7dfg8.7dfg8.sandbox258.opentlc.com/