{{- if .Values.consoleLink.enable | default true }}
apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: {{ $.Values.appName }}-console-link
  namespace: {{ $.Values.namespace }}
spec:
  applicationMenu:
    section: {{ .Values.consoleLink.section }}
    imageURL: {{ .Values.consoleLink.base64image }}
  href: 'https://{{ $.Values.appName }}-route-{{ $.Values.namespace }}.{{ coalesce $.Values.consoleLink.localClusterDomain $.Values.consoleLink.hubClusterDomain }}'
  location: {{ .Values.consoleLink.location }}
  text: {{ .Values.consoleLink.text }}

{{- end }}

#http://credit-fraud-detection-demo-route-credit-fraud-model.apps.cluster-7dfg8.7dfg8.sandbox258.opentlc.com/